### ISSUE TITLE
List of install requirements as 'requirements.txt'

### ISSUE THREAD

**Issue by sergeicu** [ejcanalesr/multicomponent-T2-toolbox#1]
Hi, could you please export a list of install requirements with specific versions? 

I had been debugging for some time since python, matplotlib and scipy versions did not match.

**Comment by sergeicu** [comment]
e.g. 

i had to remove this line in every .py file - 
`matplotlib.rcParams['text.latex.unicode']=True` 

as this functionality is deprecated in new matlplotlib versions

**Comment by sergeicu** [comment]
Also - 'xrange' is deprecated in python3. It is now called simply 'range'

**Comment by sergeicu** [comment]
I am going to push a copy of this repository to my own username, which is compatible with python3 and the more recent versions of matplotlib and scipy. 

I created an installation `requirements.txt` file using `pipreqs` library also. 

Please feel free to git clone and run `git diff` on the latest commit to see all changes that were made.

**Comment by sergeicu** [comment]
https://github.com/sergeicu/multicomponent-T2-toolbox/

**Comment by sergeicu** [comment]
Also requires `dvipng` to be installed  (else matplotlib fails) - 

on centos - 

`sudo yum -y install texlive-dvipng` 

on ubuntu - 
` sudo apt-get install -y dvipng `

**Comment by sergeicu** [comment]
I made a `pull request` to merge changes for python3 compatibility.

**Comment by ejcanalesr** [comment]
Dear sergeicu,

Thanks a lot for your help!

I am now on holiday, and I will integrate your changes in September.

Thanks a lot!

All the best,

Erick


________________________________

**Comment by ejcanalesr** [comment]
Finally, I merged your changes! Thanks a lot! Erick

**Comment by harrisoncbrammell** [comment]
Hello, I wanted to make you all aware of some installation issues that I have been dealing with so others who have a similar problem might be able solve it easier than me. 

First, scipy_image fails because it cant find numpy. Then I tried moving numpy above it in the requirments, which lead to numpy failing because of an error with cythonize. Installing cythonize did not fix this issue. The pip output can be seen below. 

`Collecting numpy==1.19.2
  Using cached numpy-1.19.2.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def __init__(self, seed=None):
              BitGenerator.__init__(self, seed)
              self.rng_state.pcg_state = &self.pcg64_random_state

              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &pcg64_uint64
                                         ^
      ------------------------------------------------------------

      _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-jby7wbbb/numpy_d7cc508fa9b945aabaab369d8bfcd076/tools/cythonize.py", line 235, in <module>
          main()
        File "/tmp/pip-install-jby7wbbb/numpy_d7cc508fa9b945aabaab369d8bfcd076/tools/cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-jby7wbbb/numpy_d7cc508fa9b945aabaab369d8bfcd076/tools/cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-jby7wbbb/numpy_d7cc508fa9b945aabaab369d8bfcd076/tools/cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-jby7wbbb/numpy_d7cc508fa9b945aabaab369d8bfcd076/tools/cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/mnt/e/Development/MRI-sure-program/epg-tools/multicomponent-T2-toolbox/venv/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "/mnt/e/Development/MRI-sure-program/epg-tools/multicomponent-T2-toolbox/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/e/Development/MRI-sure-program/epg-tools/multicomponent-T2-toolbox/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/e/Development/MRI-sure-program/epg-tools/multicomponent-T2-toolbox/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-qnsfk49y/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-qnsfk49y/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 248, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-qnsfk49y/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 499, in <module>
          setup_package()
        File "setup.py", line 479, in setup_package
          generate_cython()
        File "setup.py", line 274, in generate_cython
          raise RuntimeError("Running cythonize failed!")
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip`

I am still trying to install this myself still but if you all have a good solution to this I would love to hear it.

**Comment by harrisoncbrammell** [comment]
It appears that the required version of numpy is not compatible with py3.10. We would need a prebuilt wheel for this to work and pip cannot find any.
